name: 'Install Siskin'
author: 'Oldes'
description: 'GitHub Action to install Siskin Builder tool'

branding:
  icon: 'download-cloud'  
  color: 'red'

inputs:
  version:
    description: 'Siskin version to download'
    required: true
    default: '0.16.0'
  arch:
    description: 'Required architecture (x86, x86_64, aarch64)'
    required: true
    default: 'x86_64'
  name:
    description: 'Local file name'
    required: true
    default: 'siskin'

outputs:
  SISKIN:
    description: "Path to Siskin executable"
    value: ${{ steps.download-siskin.outputs.SISKIN }}
runs:
  using: "composite"
  steps:
    - id: download-siskin
      name: Downloading Siskin
      shell: bash
      env:
        URL: https://github.com/Siskin-Framework/Builder/releases/download
        VERSION: ${{ inputs.version }}
        NAME: ${{ inputs.name }}
      run: |
        echo Expected version: $VERSION
        export DOWNLOAD_URL=$URL/$VERSION

        if [ "$RUNNER_OS" == "Linux" ]; then
          export FILE=siskin-linux-${{ inputs.arch }}
          echo Dowloading: $DOWNLOAD_URL/${FILE}.gz
          wget -q $DOWNLOAD_URL/${FILE}.gz
          gunzip ./${FILE}.gz
          mv ./${FILE} ./$NAME
          chmod +x ./$NAME
          echo "SISKIN=$(realpath $NAME)" >> $GITHUB_OUTPUT

        elif [ "$RUNNER_OS" == "macOS" ]; then
          export FILE=siskin-macos-${{ inputs.arch }}
          echo Dowloading: $DOWNLOAD_URL/${FILE}.gz
          wget -q $DOWNLOAD_URL/${FILE}.gz
          gunzip ./${FILE}.gz
          mv ./${FILE} ./$NAME
          chmod +x ./$NAME
          echo "SISKIN=$(echo $PWD/$NAME)" >> $GITHUB_OUTPUT
        
        elif [ "$RUNNER_OS" == "Windows" ]; then
          export FILE=siskin-windows-${{ inputs.arch }}.exe
          echo Downloading: $DOWNLOAD_URL/$FILE
          curl -sSLJO $DOWNLOAD_URL/$FILE
          mv ./$FILE ./$NAME.exe
          echo "SISKIN=$(realpath $NAME.exe)" >> $GITHUB_OUTPUT
        fi
